/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WopSignature {
    }
}
declare global {
    interface HTMLWopSignatureElement extends Components.WopSignature, HTMLStencilElement {
    }
    var HTMLWopSignatureElement: {
        prototype: HTMLWopSignatureElement;
        new (): HTMLWopSignatureElement;
    };
    interface HTMLElementTagNameMap {
        "wop-signature": HTMLWopSignatureElement;
    }
}
declare namespace LocalJSX {
    interface WopSignature {
    }
    interface IntrinsicElements {
        "wop-signature": WopSignature;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wop-signature": LocalJSX.WopSignature & JSXBase.HTMLAttributes<HTMLWopSignatureElement>;
        }
    }
}
